# Data Science
## Home task 1

In [1]:
#import module numpy
import numpy as np

#### 1. Create a one-dimensional array (vector) with the first 10 positive integers and print its value.

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


#### 2. Create a two-dimensional array (matrix) of size 3x3, fill it with zeros and print its value. 

In [4]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Create an array of size 5x5, fill it with random integers in the range from 1 to 10 and print its value.

In [6]:
np.random.randint(1, 11, size=(5, 5))

array([[ 3,  1,  7,  8,  5],
       [ 6,  5,  7,  4,  9],
       [10,  9,  2,  3, 10],
       [ 9,  2,  4,  3,  8],
       [ 5, 10,  6,  5,  3]])

In [7]:
a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 3  2  3  7  4]
 [ 5  7  8  5  2]
 [ 2  7  7  2  3]
 [ 7 10  3  3  4]
 [10  9  6  3  5]]


#### 4. Create an array of size 4x4, fill it with random real numbers in the range from 0 to 1 and print its value.

In [8]:
a = np.random.uniform(low=0.0, high=1.0, size=(4, 4))
print(a)

[[0.78407063 0.33695411 0.11806425 0.0218881 ]
 [0.52216285 0.58537975 0.09895185 0.59482942]
 [0.68231431 0.22051174 0.09664322 0.81956478]
 [0.11257973 0.2624984  0.47574333 0.34196992]]


#### 5. Create two one-dimensional arrays of size 5, fill them with random integers in the range from 1 to 10, and perform elementwise addition, subtraction, and multiplication operations on them.

In [9]:
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))

In [10]:
print(a+b)

[14 10 12  5 18]


In [11]:
print(a-b)

[ 6 -4 -4  3  2]


In [12]:
print(a/b)

[2.5        0.42857143 0.5        4.         1.25      ]


#### 6. Create two vectors of size 7, fill them with random numbers and find their scalar product.

In [13]:
a = np.random.random(7)
b = np.random.random(7)
print(np.dot(a, b))

1.307303061248996


#### 7. Create two matrices of size 2x2 and 2x3, fill them with random integers in the range from 1 to 10, and multiply them.

In [14]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(np.dot(a, b))

[[79 54 84]
 [17 12 17]]


#### 8. Create a 3x3 matrix, fill it with random integers in the range from 1 to 10, and find its inverse.

In [15]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)

In [16]:
print(a)

[[ 7  1  1]
 [ 5  1  3]
 [ 8  2 10]]


In [17]:
print(a_inv)

[[ 1.  -2.   0.5]
 [-6.5 15.5 -4. ]
 [ 0.5 -1.5  0.5]]


#### 9. Create a 4x4 matrix, fill it with random real numbers in the range from 0 to 1 and transpose it.

In [18]:
a = np.random.uniform(0, 1, size=(4, 4))

In [19]:
print(a)

[[0.15664996 0.80879857 0.14858301 0.09096468]
 [0.94851932 0.05305703 0.98299287 0.11594427]
 [0.69869933 0.30832277 0.83434208 0.1714608 ]
 [0.61468361 0.83711757 0.53816981 0.40226877]]


In [20]:
print(a.T)

[[0.15664996 0.94851932 0.69869933 0.61468361]
 [0.80879857 0.05305703 0.30832277 0.83711757]
 [0.14858301 0.98299287 0.83434208 0.53816981]
 [0.09096468 0.11594427 0.1714608  0.40226877]]


#### 10. Create a 3x4 matrix and a 4-dimensional vector, fill them with random integers in the range 1 to 10, and multiply the matrix by the vector.

In [21]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4))

In [22]:
print(a)

[[ 6  4  7  7]
 [ 4  2  5  9]
 [ 5  5  1 10]]


In [23]:
print(b)

[10  3  7  7]


In [24]:
print(a * b)

[[60 12 49 49]
 [40  6 35 63]
 [50 15  7 70]]


#### 11. Create a 2x3 matrix and a vector of size 3, fill them with random real numbers in the range 0 to 1, and multiply the matrix by the vector.

In [25]:
a = np.random.uniform(low=0.0, high=1.0, size=(2, 3))
b = np.random.uniform(low=0.0, high=1.0, size=(3))

In [26]:
print(a)

[[0.26926033 0.81898114 0.66137652]
 [0.86810648 0.18257007 0.22185893]]


In [27]:
print(b)

[0.15240917 0.29556845 0.04633211]


In [28]:
print(a * b)

[[0.04103774 0.24206498 0.03064297]
 [0.13230739 0.05396195 0.01027919]]


#### 12. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10, and perform their elementwise multiplication.

In [29]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

In [30]:
print(a)

[[6 4]
 [9 4]]


In [31]:
print(b)

[[4 9]
 [5 5]]


In [32]:
print(a * b)

[[24 36]
 [45 20]]


#### 13. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and find their product.

In [33]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

In [34]:
print(a)

[[10 10]
 [ 3 10]]


In [35]:
print(b)

[[8 1]
 [7 4]]


In [36]:
print(np.dot(a, b))

[[150  50]
 [ 94  43]]


#### 14. Create a 5x5 matrix, fill it with random integers in the range from 1 to 100 and find the sum of the matrix elements.

In [37]:
a = np.random.randint(1, 101, size=(5, 5))

In [38]:
print(a)

[[61 66 64 58 90]
 [16 95 59 35 87]
 [67 93 94 49 17]
 [67 64 96 58 76]
 [67 55 76 52 34]]


In [39]:
print(a.sum())

1596


#### 15. Create two matrices of size 4x4, fill them with random integers in the range from 1 to 10 and find their difference.

In [40]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))

In [41]:
print(a)

[[ 6  1  4  3]
 [ 6  9  8 10]
 [ 9 10  1  2]
 [ 9  2  4 10]]


In [42]:
print(b)

[[ 6  3  5  3]
 [ 2  1 10 10]
 [ 8 10 10  6]
 [ 8  2  8  3]]


In [43]:
print(a - b)

[[ 0 -2 -1  0]
 [ 4  8 -2  0]
 [ 1  0 -9 -4]
 [ 1  0 -4  7]]


#### 16. Create a 3x3 matrix, fill it with random real numbers in the range from 0 to 1, and find the column vector containing the sum of the elements of each row of the matrix.

In [44]:
a = np.random.uniform(low=0.0, high=1.0, size=(3, 3))
b = np.array([sum(a[0, :3]), sum(a[1, :3]), sum(a[2, :3])])

In [45]:
print(a)

[[0.68493707 0.17540509 0.97043218]
 [0.65925203 0.44396715 0.85601585]
 [0.90155126 0.01711347 0.75932258]]


In [46]:
print(b.reshape((3, 1)))

[[1.83077434]
 [1.95923504]
 [1.67798731]]


#### 17. Create a 3x4 matrix with any integers and create a matrix with the squares of these numbers.

In [47]:
a = np.random.randint(-11, 11, size=(3, 4))

In [48]:
print(a)

[[  7   0   8 -10]
 [  4 -11   4 -11]
 [  4 -10  -3   4]]


In [49]:
print(np.square(a))

[[ 49   0  64 100]
 [ 16 121  16 121]
 [ 16 100   9  16]]


#### 18. Create a vector of size 4, fill it with random integers in the range from 1 to 50, and find the vector with the square roots of these numbers.

In [50]:
a = np.random.randint(1, 51, size=(4))

In [51]:
print(a)

[ 9 44 31 48]


In [52]:
print(np.sqrt(a))

[3.         6.63324958 5.56776436 6.92820323]
